### PR TITLE
Fix BJORKSNAS cost

### PR DESCRIPTION
**Pull request by wohali**
99, not 999 Coins!

### CODE REVIEW

**Comment by The-Bees-Decree-Server** [comment]
mate... you can change the cost in TheBeesDecree.VALKEA.cfg...

**Comment by wohali** [comment]
I know! I was just letting you know the default value isn't correct in the README. It's just a PR to fix the docs.

Thank you for your hard work on this mod.

**Comment by The-Bees-Decree-Server** [comment]
> I know! I was just letting you know the default value isn't correct in the README. It's just a PR to fix the docs.
> 
> Thank you for your hard work on this mod.

My bad, i miss read the fork.
Thank you

**Comment by The-Bees-Decree-Server** [comment]
Wait lol

It's intended to be 999, not 99.

**Comment by wohali** [comment]
😂 well, I just did a vanilla install and it's:

```
BJORKSNASxx: FineWood:1,QueenBee:1,Coins:99
ValkeaTool: FineWood:1,Iron:1,Coins:99
```

🤷🏼‍♀️ Want me to close this PR?

**Comment by The-Bees-Decree-Server** [comment]
Ahhh i see now.
I was thinking you were referring to the main BJROKSNAS not the modular.
ill deff take a look into those!

Sorry for all the confusion

**Comment by The-Bees-Decree-Server** [comment]
Should be all fix-ed 😃

**Pull request closed without merging**
